"""Pure Pydantic domain layer for statblock v1."""

from statblocks_v1.domain.canonicalization import (
    CANONICALIZER_VERSION,
    canonical_definition_bytes,
    canonicalize_definition,
)
from statblocks_v1.domain.digests import DIGEST_ALGORITHM, compute_definition_digest
from statblocks_v1.domain.primitives import (
    Activation,
    AutomationSupport,
    DiceExpression,
    Distance,
    Duration,
    Effect,
    RangeProfile,
    ResourceCost,
    TargetProfile,
    Trigger,
    Usage,
)
from statblocks_v1.domain.profiles import (
    AbilityScores,
    ChallengeProfile,
    CommunicationProfile,
    CreatureIdentity,
    DefenseProfile,
    LairProfile,
    MovementProfile,
    ProficiencyProfile,
    ResourcePool,
    RulesetRef,
    SenseProfile,
    StatblockFlavorText,
    VitalityProfile,
)
from statblocks_v1.domain.receipts import (
    ValidationIssueV1,
    ValidationMode,
    ValidationReceiptV1,
    ValidationSeverity,
    ValidationStatus,
)
from statblocks_v1.domain.rule_elements import Mechanic, RuleElement, StatblockDefinitionV1
from statblocks_v1.domain.validation import validate_definition

__all__ = [
    "AbilityScores",
    "Activation",
    "AutomationSupport",
    "CANONICALIZER_VERSION",
    "ChallengeProfile",
    "CommunicationProfile",
    "CreatureIdentity",
    "DefenseProfile",
    "DiceExpression",
    "DIGEST_ALGORITHM",
    "Distance",
    "Duration",
    "Effect",
    "LairProfile",
    "Mechanic",
    "MovementProfile",
    "ProficiencyProfile",
    "RangeProfile",
    "ResourceCost",
    "ResourcePool",
    "RuleElement",
    "RulesetRef",
    "SenseProfile",
    "StatblockDefinitionV1",
    "StatblockFlavorText",
    "TargetProfile",
    "Trigger",
    "Usage",
    "ValidationIssueV1",
    "ValidationMode",
    "ValidationReceiptV1",
    "ValidationSeverity",
    "ValidationStatus",
    "VitalityProfile",
    "canonical_definition_bytes",
    "canonicalize_definition",
    "compute_definition_digest",
    "validate_definition",
]
