"""Deterministic schema publication helpers for the v1 definition."""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

from statblocks_v1.domain.rule_elements import StatblockDefinitionV1

SCHEMA_ARTIFACT_DIRECTORY = Path(__file__).with_name("schema_artifacts")
_UNSUPPORTED_OPENAI_KEYWORDS = {
    "$schema",
    "default",
    "description",
    "examples",
    "title",
    "discriminator",
}


def canonical_json_schema() -> dict[str, Any]:
    """Return Pydantic's canonical JSON Schema for the contract."""
    return StatblockDefinitionV1.model_json_schema()


def openai_strict_json_schema() -> dict[str, Any]:
    """Compile canonical schema into OpenAI Structured Outputs strict form.

    The compiler removes documentation-only metadata, closes every object, and
    makes every object property required. Optionality remains represented by
    explicit null unions generated by Pydantic.
    """
    return _transform_for_openai(copy.deepcopy(canonical_json_schema()))


def write_schema_artifacts(directory: Path = SCHEMA_ARTIFACT_DIRECTORY) -> tuple[Path, Path]:
    """Write stable, reviewable schema artifacts and return their paths."""
    directory.mkdir(parents=True, exist_ok=True)
    canonical_path = directory / "statblock_definition_v1.canonical.schema.json"
    strict_path = directory / "statblock_definition_v1.openai-strict.schema.json"
    _write_json(canonical_path, canonical_json_schema())
    _write_json(strict_path, openai_strict_json_schema())
    return canonical_path, strict_path


def _transform_for_openai(node: Any) -> Any:
    if isinstance(node, list):
        return [_transform_for_openai(item) for item in node]
    if not isinstance(node, dict):
        return node

    transformed = {
        key: _transform_for_openai(value)
        for key, value in node.items()
        if key not in _UNSUPPORTED_OPENAI_KEYWORDS
    }
    if transformed.get("type") == "object" or "properties" in transformed:
        transformed["additionalProperties"] = False
        if "properties" in transformed:
            transformed["required"] = list(transformed["properties"])
    return transformed


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
