"""Export the isolated DungeonBuddy statblock v1 OpenAPI contract deterministically."""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OPENAPI_PATH = ROOT / "openapi" / "dungeonbuddy-statblocks-v1.json"
TYPESCRIPT_PATH = ROOT / "generated" / "dungeonbuddy-statblocks-v1" / "client.ts"
FIXTURE_PATH = ROOT / "Docs" / "Design" / "fixtures" / "dungeonbuddy-statblock-v1-api"

_TS_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def build_openapi() -> dict[str, Any]:
    from statblocks_v1.testing import create_contract_app

    return create_contract_app().openapi()


def serialize_openapi(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def schema_fingerprint(schema: dict[str, Any]) -> str:
    return f"sha256:{hashlib.sha256(serialize_openapi(schema).encode()).hexdigest()}"


def _ts_name(name: str) -> str:
    """Turn OpenAPI component names into valid TypeScript identifiers."""

    sanitized = name.replace("-", "_")
    if not _TS_IDENT.match(sanitized):
        raise ValueError(f"cannot sanitize OpenAPI component name into a TS identifier: {name!r}")
    return sanitized


def _type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ts_name(schema["$ref"].rsplit("/", 1)[-1])
    if schema.get("type") == "null":
        return "null"
    if "const" in schema and "enum" not in schema and "$ref" not in schema:
        return json.dumps(schema["const"])
    if "enum" in schema and "type" not in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "allOf" in schema:
        parts: list[str] = []
        for option in schema["allOf"]:
            rendered = _type(option)
            if rendered in {"unknown", "Record<string, unknown>"}:
                continue
            if rendered not in parts:
                parts.append(rendered)
        if not parts:
            return "unknown"
        if len(parts) == 1:
            return parts[0]
        return " & ".join(parts)
    if "anyOf" in schema or "oneOf" in schema:
        options = schema.get("anyOf") or schema.get("oneOf") or []
        parts = []
        for option in options:
            rendered = _type(option)
            if rendered not in parts:
                parts.append(rendered)
        if "null" in parts and len(parts) > 1:
            non_null = [part for part in parts if part != "null"]
            return " | ".join([*non_null, "null"])
        return " | ".join(parts)
    if schema.get("nullable") is True:
        base = {key: value for key, value in schema.items() if key != "nullable"}
        rendered = _type(base)
        return rendered if rendered.endswith("| null") else f"{rendered} | null"
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_type(schema.get('items', {}))}>"
    if kind == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = [
            f"{name}{'' if name in required else '?'}: {_type(value)}"
            for name, value in properties.items()
        ]
        return "{ " + "; ".join(fields) + " }"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "string":
        if "enum" in schema:
            return " | ".join(json.dumps(value) for value in schema["enum"])
        if "const" in schema:
            return json.dumps(schema["const"])
        return "string"
    return "unknown"


def render_typescript(schema: dict[str, Any]) -> str:
    fingerprint = schema_fingerprint(schema)
    components = schema["components"]["schemas"]
    declarations = "\n\n".join(
        f"export type {_ts_name(name)} = {_type(component)};"
        for name, component in sorted(components.items())
    )
    return f"""// Generated by scripts/export_dungeonbuddy_statblock_openapi.py; DO NOT EDIT.
// Source: openapi/dungeonbuddy-statblocks-v1.json
// Source fingerprint: {fingerprint}

{declarations}

export class DungeonBuddyStatblocksV1Client {{
  constructor(private readonly baseUrl: string, private readonly internalKey: string) {{}}

  async request<T>(path: string, init: RequestInit = {{}}): Promise<T> {{
    const response = await fetch(`${{this.baseUrl}}${{path}}`, {{
      ...init,
      headers: {{
        "X-DungeonBuddy-Internal-Key": this.internalKey,
        "Content-Type": "application/json",
        ...init.headers,
      }},
    }});
    if (!response.ok) throw await response.json();
    return response.json() as Promise<T>;
  }}
}}
"""


def export_artifacts() -> str:
    schema = build_openapi()
    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPESCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(serialize_openapi(schema), encoding="utf-8")
    TYPESCRIPT_PATH.write_text(render_typescript(schema), encoding="utf-8")
    export_fixture_pack()
    return schema_fingerprint(schema)


def export_fixture_pack() -> None:
    """Publish deterministic API examples that match live route semantics."""
    from datetime import datetime, timezone

    from statblocks_v1 import CONTRACT_NAME, CONTRACT_VERSION
    from statblocks_v1.api.models import GenerateCandidateRequestV1
    from statblocks_v1.application.commands import CallerProvenanceV1, GenerateStatblockCommandV1
    from statblocks_v1.application.generation import (
        GenerateOutcomeV1,
        GenerationFailureV1,
        GenerationServiceV1,
    )
    from statblocks_v1.application.provider import ProviderOutcomeV1
    from statblocks_v1.application.settings import GenerationSettingsV1
    from statblocks_v1.domain.assets import AssetBindingV1
    from statblocks_v1.domain.canonicalization import canonicalize_definition
    from statblocks_v1.domain.digests import compute_definition_digest
    from statblocks_v1.domain.errors import PersistenceValidationError
    from statblocks_v1.domain.receipts import ValidationMode
    from statblocks_v1.domain.resources import (
        STATBLOCK_CONTRACT,
        STATBLOCK_CONTRACT_VERSION,
        StatblockResourceV1,
        StatblockRevisionResourceV1,
    )
    from statblocks_v1.domain.rule_elements import StatblockDefinitionV1
    from statblocks_v1.domain.validation import validate_definition
    from statblocks_v1.infrastructure.fake_provider import FakeDefinitionProvider
    from statblocks_v1.infrastructure.memory_repositories import InMemoryCandidateRepository

    fixtures_root = ROOT / "Docs" / "Design" / "fixtures" / "dungeonbuddy-statblock-v1"
    definition = StatblockDefinitionV1.model_validate(
        json.loads((fixtures_root / "simple_bruiser.json").read_text())
    )
    invalid_definition = StatblockDefinitionV1.model_validate(
        json.loads((fixtures_root / "unknown_resource_pool.json").read_text())
    )
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    binding = AssetBindingV1.model_validate(
        {
            "asset": {
                "asset_id": "asset_ironhide_portrait",
                "provider_kind": "cloudflare_images",
                "url": "https://imagedelivery.net/dungeonmind/asset_ironhide_portrait/public",
                "mime_type": "image/png",
                "alt_text": "Ironhide Brute portrait",
                "created_at": now.isoformat(),
            },
            "role": "portrait",
        }
    )
    preview_receipt = validate_definition(
        definition, ValidationMode.editor_preview, validated_at=now
    )
    persistence_receipt = validate_definition(
        definition, ValidationMode.persistence, validated_at=now
    )
    invalid_persistence_receipt = validate_definition(
        invalid_definition, ValidationMode.persistence, validated_at=now
    )
    assert not invalid_persistence_receipt.is_persistence_ready
    persistence_error = PersistenceValidationError(invalid_persistence_receipt)

    # One possible live generate exchange: omit actor/asset_options so route defaults
    # apply (no images; brief from description; digest computed from description).
    generate_request = {
        "request_id": "fixture-generate-1",
        "ruleset": definition.ruleset.model_dump(mode="json"),
        "source": {
            "name_hint": "Ironhide Brute",
            "description": "A brutal enforcer.",
        },
    }
    request = GenerateCandidateRequestV1.model_validate(generate_request)
    command = GenerateStatblockCommandV1(
        request_id=request.request_id,
        ruleset=request.ruleset,
        source=request.source,
        intent=request.intent,
        context=request.context,
        asset_options=request.asset_options,
        caller=CallerProvenanceV1(caller_scope="dungeonbuddy", actor=request.actor),
    )
    candidate_ttl_seconds = 86400
    service = GenerationServiceV1(
        provider=FakeDefinitionProvider(
            ProviderOutcomeV1.succeeded(
                definition.model_dump(mode="json"),
                latency_ms=0,
            )
        ),
        candidates=InMemoryCandidateRepository(clock=lambda: now),
        settings=GenerationSettingsV1("fixture-model", 1.0, 0, candidate_ttl_seconds),
        clock=lambda: now,
        candidate_id_factory=lambda: "cand_fixture1",
    )
    outcome = service.generate(command)
    assert not isinstance(outcome, GenerationFailureV1)
    candidate = outcome.candidate if isinstance(outcome, GenerateOutcomeV1) else outcome
    assert candidate.contract == CONTRACT_NAME
    assert candidate.contract_version == CONTRACT_VERSION
    assert candidate.generation_receipt is not None
    assert candidate.generation_receipt.actor is None
    assert candidate.generation_receipt.source_description_digest is not None
    assert candidate.assets == []
    assert candidate.asset_brief is not None
    assert candidate.asset_brief.prompt == request.source.description

    canonical = str(canonicalize_definition(definition))
    digest = compute_definition_digest(definition)
    revision = StatblockRevisionResourceV1(
        statblock_id="sb_fixture1",
        revision_id="rev_fixture1",
        contract=STATBLOCK_CONTRACT,
        contract_version=STATBLOCK_CONTRACT_VERSION,
        definition=definition,
        canonical_definition=canonical,
        definition_digest=digest,
        validation_receipt=persistence_receipt,
        provenance={"change_summary": "Accepted fixture."},
        asset_bindings=[binding],
        created_at=now,
    )
    create_request = {
        "idempotency_key": "fixture-create-1",
        "definition": definition.model_dump(mode="json"),
        "candidate_id": candidate.candidate_id,
        "change_summary": "Accepted fixture.",
        "asset_bindings": [binding.model_dump(mode="json")],
    }
    fixtures = {
        "generate-request.json": generate_request,
        "candidate-response.json": candidate.model_dump(mode="json"),
        "validate-request.json": {"definition": definition.model_dump(mode="json")},
        "validate-response.json": {
            "validation_receipt": preview_receipt.model_dump(mode="json"),
            "definition_digest": preview_receipt.definition_digest,
        },
        "create-request.json": create_request,
        "create-response.json": {
            "statblock": StatblockResourceV1(
                statblock_id="sb_fixture1",
                latest_revision_id="rev_fixture1",
                created_at=now,
                created_by="dungeonbuddy",
            ).model_dump(mode="json"),
            "revision": revision.model_dump(mode="json"),
        },
        "append-request.json": {
            **create_request,
            "idempotency_key": "fixture-append-1",
            "parent_revision_id": "rev_fixture1",
        },
        "exact-revision-response.json": revision.model_dump(mode="json"),
        "errors.json": {
            "error": {
                "code": persistence_error.code,
                "message": persistence_error.message,
                "details": persistence_error.details,
            }
        },
    }
    FIXTURE_PATH.mkdir(parents=True, exist_ok=True)
    for name, payload in fixtures.items():
        (FIXTURE_PATH / name).write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )


if __name__ == "__main__":
    print(export_artifacts())
