"""Export the isolated DungeonBuddy statblock v1 OpenAPI contract deterministically."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OPENAPI_PATH = ROOT / "openapi" / "dungeonbuddy-statblocks-v1.json"
TYPESCRIPT_PATH = ROOT / "generated" / "dungeonbuddy-statblocks-v1" / "client.ts"
FIXTURE_PATH = ROOT / "Docs" / "Design" / "fixtures" / "dungeonbuddy-statblock-v1-api"


def build_openapi() -> dict[str, Any]:
    from statblocks_v1.testing import create_contract_app

    return create_contract_app().openapi()


def serialize_openapi(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def schema_fingerprint(schema: dict[str, Any]) -> str:
    return f"sha256:{hashlib.sha256(serialize_openapi(schema).encode()).hexdigest()}"


def _type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_type(option) for option in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_type(option) for option in schema["oneOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_type(schema.get('items', {}))}>"
    if kind == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = [
            f"{name}{'' if name in required else '?'}: {_type(value)}"
            for name, value in properties.items()
        ]
        return "{ " + "; ".join(fields) + " }"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "string":
        return "string"
    return "unknown"


def render_typescript(schema: dict[str, Any]) -> str:
    fingerprint = schema_fingerprint(schema)
    components = schema["components"]["schemas"]
    declarations = "\n\n".join(
        f"export type {name} = {_type(component)};"
        for name, component in sorted(components.items())
    )
    return f"""// Generated by scripts/export_dungeonbuddy_statblock_openapi.py; DO NOT EDIT.
// Source: openapi/dungeonbuddy-statblocks-v1.json
// Source fingerprint: {fingerprint}

{declarations}

export class DungeonBuddyStatblocksV1Client {{
  constructor(private readonly baseUrl: string, private readonly internalKey: string) {{}}

  async request<T>(path: string, init: RequestInit = {{}}): Promise<T> {{
    const response = await fetch(`${{this.baseUrl}}${{path}}`, {{
      ...init,
      headers: {{
        "X-DungeonBuddy-Internal-Key": this.internalKey,
        "Content-Type": "application/json",
        ...init.headers,
      }},
    }});
    if (!response.ok) throw await response.json();
    return response.json() as Promise<T>;
  }}
}}
"""


def export_artifacts() -> str:
    schema = build_openapi()
    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPESCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(serialize_openapi(schema), encoding="utf-8")
    TYPESCRIPT_PATH.write_text(render_typescript(schema), encoding="utf-8")
    export_fixture_pack()
    return schema_fingerprint(schema)


def export_fixture_pack() -> None:
    """Publish deterministic valid API examples without contacting providers."""
    from datetime import datetime, timezone

    from statblocks_v1.domain.assets import AssetBindingV1, AssetBriefV1
    from statblocks_v1.domain.canonicalization import canonicalize_definition
    from statblocks_v1.domain.digests import compute_definition_digest
    from statblocks_v1.domain.receipts import ValidationMode
    from statblocks_v1.domain.resources import (
        GeneratedStatblockCandidateV1,
        StatblockResourceV1,
        StatblockRevisionResourceV1,
    )
    from statblocks_v1.domain.rule_elements import StatblockDefinitionV1
    from statblocks_v1.domain.validation import validate_definition

    definition = StatblockDefinitionV1.model_validate(json.loads(
        (ROOT / "Docs" / "Design" / "fixtures" / "dungeonbuddy-statblock-v1" / "simple_bruiser.json").read_text()
    ))
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    binding = AssetBindingV1.model_validate({
        "asset": {"asset_id": "asset_ironhide_portrait", "provider_kind": "cloudflare_images",
                  "url": "https://imagedelivery.net/dungeonmind/asset_ironhide_portrait/public",
                  "mime_type": "image/png", "alt_text": "Ironhide Brute portrait",
                  "created_at": now.isoformat()},
        "role": "portrait",
    })
    receipt = validate_definition(definition, ValidationMode.persistence, validated_at=now)
    canonical = str(canonicalize_definition(definition))
    digest = compute_definition_digest(definition)
    candidate = GeneratedStatblockCandidateV1(
        candidate_id="cand_fixture1",
        definition=definition,
        validation_receipt=receipt,
        asset_brief=AssetBriefV1(prompt="Ironhide Brute portrait"),
        assets=[binding.asset],
        created_at=now,
        expires_at=datetime(2026, 1, 2, tzinfo=timezone.utc),
    )
    revision = StatblockRevisionResourceV1(
        statblock_id="sb_fixture1",
        revision_id="rev_fixture1",
        definition=definition,
        canonical_definition=canonical,
        definition_digest=digest,
        validation_receipt=receipt,
        provenance={"change_summary": "Accepted fixture."},
        asset_bindings=[binding],
        created_at=now,
    )
    create_request = {
        "idempotency_key": "fixture-create-1", "definition": definition.model_dump(mode="json"),
        "candidate_id": candidate.candidate_id, "change_summary": "Accepted fixture.",
        "asset_bindings": [binding.model_dump(mode="json")],
    }
    fixtures = {
        "generate-request.json": {"request_id": "fixture-generate-1", "ruleset": definition.ruleset.model_dump(),
                                  "source": {"name_hint": "Ironhide Brute", "description": "A brutal enforcer."}},
        "candidate-response.json": candidate.model_dump(mode="json"),
        "validate-request.json": {"definition": definition.model_dump(mode="json")},
        "validate-response.json": {"validation_receipt": receipt.model_dump(mode="json"), "definition_digest": digest},
        "create-request.json": create_request,
        "create-response.json": {"statblock": StatblockResourceV1(
            statblock_id="sb_fixture1", latest_revision_id="rev_fixture1", created_at=now,
            created_by="dungeonbuddy",
        ).model_dump(mode="json"), "revision": revision.model_dump(mode="json")},
        "append-request.json": {**create_request, "idempotency_key": "fixture-append-1",
                                "parent_revision_id": "rev_fixture1"},
        "exact-revision-response.json": revision.model_dump(mode="json"),
        "errors.json": {"error": {"code": "definition_invalid",
                                   "message": "The proposed statblock definition failed validation."}},
    }
    FIXTURE_PATH.mkdir(parents=True, exist_ok=True)
    for name, payload in fixtures.items():
        (FIXTURE_PATH / name).write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    print(export_artifacts())
